CREATE SCHEMA RSS ;

CREATE SEQUENCE RSS.RSS_ITEM_SEQ START WITH 1 ORDER;

CREATE TABLE RSS.RSS_ITEM
(
    ID  NUMBER(19) NOT NULL,
    URL VARCHAR2(100) NOT NULL,
    TITLE VARCHAR2(255),
    DESCRIPTION VARCHAR2(1000),
    PUBLICATION TIMESTAMP(6),
    UPDATE_TIME TIMESTAMP(6),
    IMAGE_URL VARCHAR2(200 CHAR),
    PRIMARY KEY (ID)
)


